behaviors:
  CarAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 120 #10
      buffer_size: 12000 #100
      learning_rate: 0.0003 #3.0e-4
      beta: 0.001 #5.0e-4
      epsilon: 0.2
      lambd: 0.95 #0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true #false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000 #64
    summary_freq: 12000 #10000
    threaded: true